# Generated by Django 4.0.4 on 2022-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model', models.CharField(choices=[(1, 'Jeep'), (2, 'Cabriolet'), (3, 'Sedan'), (4, 'Minivan'), (5, 'Pick-Up')], max_length=100)),
                ('year', models.DateField()),
                ('color', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
